<?php

namespace CommandeBundle\Repository;

/**
 * lignecmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lignecmdRepository extends \Doctrine\ORM\EntityRepository
{
}
